
# Made by NazarbekAlda!

# REQUIRED: WorldGuard, PlaceholderAPI, PlaceHolderAPI extension WorldGuard.

# Plugin has own placeholders!
#  %koth_(koth_name)_king% => Current leader (PLAYER NAME)
#  %koth_(koth_name)_timeleft% => Shows how much time is left to run. (NUMBER)
#  %koth_(koth_name)_player_countdown% => Shows how long the player stood. (NUMBER)
#  %koth_(koth_name)_status% => Gives status about koth (TEXT active or non-active)

Koth:
  Countdown: 600 # In seconds.
  CountdownWhenKoth: 30 # In seconds.

  Region: KothRegion # Region that will be KOTH. Please set up it first.



  # Message formatting is: Kuori adventure MiniMessage.
  # Html like.
  # Easy edit here: https://webui.adventure.kyori.net/

  BroadcastStart:
    - "<green><bold>KOTH started."

  BroadcastNobody:
    - "<red><bold>NOBODY WON :(((!!!"

  # Placeholder support here  :
  BroadcastWinner:
    - "<RED><BOLD>%player_name% won" #  winner message.
    - "<blue>EZZZ"
  RewardCommands:
    - "give %player_name% diamond 1" # commands.


  # Do not touch.
  # <<Unix>> time stamp database.
  # Startup
  UNIXend: "0"
  # End of koth
  UNIXKothEND: "0"

  # Koth status
  # It helps keep timer on server restart or
  # plugin restart.
  KothRunning: false