
# Made by NazarbekAlda!

# REQUIRED: WorldGuard, PlaceholderAPI, PlaceHolderAPI extension WorldGuard.

# Plugin has own placeholders!
#  %(KOTH_NAME)_king% => Current leader (PLAYER NAME)
#  %(KOTH_NAME)_timeleft% => Shows how much time is left to run. (NUMBER)
#  %(KOTH_NAME)_player_countdown% => Shows how long the player stood. (NUMBER)
#  %(KOTH_NAME)_status% => Gives status about koth (TEXT active or non-active)

Koth:
  Countdown: 600 # In seconds.
  CountdownWhenKoth: 30 # In seconds.

  Region: KothRegion # Region that will be KOTH. Please set up it first.



  # Message formatting is: Kuori adventure MiniMessage.
  # Html like.
  # Easy edit here: https://webui.adventure.kyori.net/


  BroadcastStart:
    - "<green><bold>Koth - KOTH started."

  BroadcastNobody:
    - "<red><bold>Koth - NOBODY WON :(((!!!"

  # Placeholder support here  :
  BroadcastWinner:
    - "Koth - "
    - "<RED><BOLD>%player_name% won" #  winner message.
    - "<blue>EZZZ"
  RewardCommands:
    - "give %player_name% diamond 1" # commands.